server:
  port: 8081 # 服务端口号
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false # 数据库连接url
    username: root # 数据库用户名
    password: wsl521314.. # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
mybatis:
  typeAliasesPackage: com.exambner.user # 搜索指定包别名
  mapperLocations: classpath:mapper/**/*.xml # 配置mapper的扫描，找到所有的mapper.xml映射文件
logging:
  level:
    com.exambner.user: debug # 设置日志级别，并指定日志范围com.exambner.user包
  pattern:
    dateformat: MM-dd HH:mm:ss # 指定日志里面的日期输出格式